# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM_Calculator' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM_Calculator

pod 'RxSwift','~> 5'
pod 'RxCocoa'
end
